version: '3.3'
networks:
  sender:
services:
  api:
    build:
      context: .
      dockerfile: development.dockerfile
    ports:
      - '8025:8025'
    volumes:
      - ./src:/app
      - ./.env-production:/.env
    networks:
      - sender
